name: "codeartifact-login-yarn"
description: "Get codeartifact token and setup yarn to use it"

inputs:
  working-dir:
    description: "Run action in subdirectory"
    required: false
    default: "."
  scope:
    description: "Define token in local or global configuration (default: local)"
    required: false
    default: "local"
  arn:
    description: "Codeartifact arn"
    required: true

outputs:
  token:
    description: "The codeartifact token"
    value: ${{steps.token.outputs.token}}

runs:
  using: composite
  steps:
    - name: Decompose and check ARN
      id: arn-check
      shell: bash
      run: |
        ARN=($(echo "${{inputs.arn}}" | tr ':' ' '))
        REPO=($(echo "${ARN[5]}" | tr '/' ' '))

        SERVICE=${ARN[2]}
        RESOURCE=${REPO[0]}

        if [ "$SERVICE" != 'codeartifact' ]; then
          echo "This ARN do not refer to codeartifact"
          exit 1
        fi

        if [ "$RESOURCE" != 'repository' ]; then
          echo "This ARN do not refer to a repository"
          exit 1
        fi

        REGION=${ARN[3]}
        OWNER=${ARN[4]}
        DOMAIN=${REPO[1]}
        REGISTRY=${REPO[2]}

        echo "REGION=$REGION" >> $GITHUB_ENV
        echo "OWNER=$OWNER" >> $GITHUB_ENV
        echo "DOMAIN=$DOMAIN" >> $GITHUB_ENV
        echo "REGISTRY=$REGISTRY" >> $GITHUB_ENV

    - name: Get codeartifact token
      id: token
      shell: bash
      run: |
        TOKEN=$(aws codeartifact get-authorization-token \
          --domain ${DOMAIN} \
          --domain-owner ${OWNER} \
          --region ${REGION} \
          --query authorizationToken \
          --output text \
          )
          
        echo "::add-mask::$TOKEN"
        echo "token=$TOKEN" >> $GITHUB_OUTPUT

    - name: Config yarn
      shell: bash
      working-directory: ${{inputs.working-directory}}
      run: |
        URL=https://${DOMAIN}-${OWNER}.d.codeartifact.${REGION}.amazonaws.com/npm/${REGISTRY}/

        if [ "${{inputs.scope}}" == 'global' ]; then
          SCOPE='-H'
        fi

        yarn config set ${SCOPE} "npmRegistries['${URL}'].npmAuthToken" "${{steps.token.outputs.token}}"
        yarn config set ${SCOPE} "npmRegistries['${URL}'].npmAlwaysAuth" "true"
